#!/usr/bin/env bash
# Copy this file to config.sh and fill in your values.
# config.sh is gitignored — never commit it.
#
# Run ./setup.sh to generate this file interactively.

# ── Personal board ────────────────────────────────────────────────────────────
# Your GitHub username (owner of the personal board)
BOARD_OWNER="your-github-username"

# The project NUMBER from the board URL:
# https://github.com/users/<owner>/projects/<NUMBER>
BOARD_NUMBER="3"

# Your GitHub username to filter assigned issues
ASSIGNEE="your-github-username"

# ── Repos to sync ─────────────────────────────────────────────────────────────
# Space-separated list of "owner/repo" pairs.
# Generated by setup.sh — you can edit this list manually at any time.
REPOS=(
  # "myorg/repo-one"
  # "myorg/repo-two"
  # "another-org/some-repo"
)

# ── Status field ──────────────────────────────────────────────────────────────
# Node ID of the Status single-select field on your personal board.
# Populated automatically by setup.sh.
STATUS_FIELD_ID=""

# The exact name of the "Done" status option on your personal board.
# Used when marking stale issues (closed or unassigned).
DONE_STATUS="✅ Done"

# ── State ─────────────────────────────────────────────────────────────────────
# Where to store the sync state between runs.
STATE_FILE="${HOME}/.local/state/sync-gh-board-state.json"
