#!/usr/bin/env bash
# sync.sh — Bidirectional sync between your personal GitHub Projects board
#            and the origin project boards across your tracked repos.
#
# Pull:  Open issues assigned to you → added to personal board.
#        New items inherit their status from the origin project.
#        Origin status changes → reflected on personal board
#        (unless you moved the card more recently — personal board wins).
# Push:  You move a card on personal board → status pushed to ALL origin
#        projects the issue belongs to (best-effort; skips if status not found).
# Stale: Issue closed or unassigned → moved to Done on personal board.
#
# Requires: config.sh (generated by setup.sh), gh CLI authenticated.
# Optional: status_map.json (generated by setup.sh for name mismatches).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.sh"
STATUS_MAP_FILE="$SCRIPT_DIR/status_map.json"

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "ERROR: config.sh not found. Run ./setup.sh first." >&2
  exit 1
fi

# shellcheck source=config.sh
source "$CONFIG_FILE"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

TMPDIR_SYNC=$(mktemp -d)
trap 'rm -rf "$TMPDIR_SYNC"' EXIT

mkdir -p "$(dirname "$STATE_FILE")"
[[ ! -f "$STATE_FILE" ]] && echo '{}' > "$STATE_FILE"

# Load status_map if present: {project_id: {origin_name: personal_name}}
STATUS_MAP="{}"
[[ -f "$STATUS_MAP_FILE" ]] && STATUS_MAP=$(cat "$STATUS_MAP_FILE")

# ── Fetch project metadata ────────────────────────────────────────────────────
PROJECT_ID=$(gh project view "$BOARD_NUMBER" --owner "$BOARD_OWNER" --format json --jq '.id')
log "Board: #$BOARD_NUMBER ($PROJECT_ID)"

PERSONAL_OPTIONS=$(gh project field-list "$BOARD_NUMBER" --owner "$BOARD_OWNER" --format json \
  --jq '[.fields[] | select(.name == "Status") | .options[]? | {name, id}]')

# ── Python normalizer (strips leading emoji for fuzzy name matching) ──────────
NORMALIZE_PY='
import re
def normalize(s):
    return re.sub(r"^[\U00010000-\U0010ffff\s\-]+", "", s).strip()
'

# ── Helper: resolve personal board option ID (emoji-normalized) ───────────────
personal_option_id() {
  local status_name="$1"
  echo "$PERSONAL_OPTIONS" | python3 -c "
$NORMALIZE_PY
import sys, json
target = normalize('''$status_name''')
for o in json.load(sys.stdin):
    if normalize(o['name']) == target:
        print(o['id'])
        break
" 2>/dev/null || true
}

# ── Helper: translate origin status name via status_map, then normalize ───────
translate_status() {
  local project_id="$1" origin_status="$2"
  python3 -c "
$NORMALIZE_PY
import sys, json
smap = $STATUS_MAP
personal_opts = $PERSONAL_OPTIONS
project_id = '$project_id'
origin_status = '$origin_status'

# Check status_map for this project
mapped = smap.get(project_id, {}).get(origin_status, origin_status)

# Now find matching personal option (emoji-normalized)
target = normalize(mapped)
for o in personal_opts:
    if normalize(o['name']) == target:
        print(o['name'])  # return the exact personal board name
        sys.exit(0)
# Not found
" 2>/dev/null || true
}

# ── Helper: set status on personal board item ─────────────────────────────────
set_personal_status() {
  local item_id="$1" status_name="$2"
  local option_id
  option_id=$(personal_option_id "$status_name")
  if [[ -z "$option_id" ]]; then
    log "  WARN: No personal board option for '$status_name' — skipping"
    return
  fi
  gh api graphql -f query="
    mutation {
      updateProjectV2ItemFieldValue(input: {
        projectId: \"$PROJECT_ID\"
        itemId: \"$item_id\"
        fieldId: \"$STATUS_FIELD_ID\"
        value: { singleSelectOptionId: \"$option_id\" }
      }) { projectV2Item { id } }
    }
  " > /dev/null
}

# ── Helper: get issue's origin project items as NDJSON ───────────────────────
get_origin_project_items() {
  local issue_url="$1"
  gh api graphql -f query="
    query {
      resource(url: \"$issue_url\") {
        ... on Issue {
          projectItems(first: 20) {
            nodes {
              id
              project { id title }
              fieldValueByName(name: \"Status\") {
                ... on ProjectV2ItemFieldSingleSelectValue { name optionId }
              }
            }
          }
        }
      }
    }
  " --jq '.data.resource.projectItems.nodes[] |
      {itemId: .id, projectId: .project.id, projectTitle: .project.title,
       status: (.fieldValueByName.name // "")}' 2>/dev/null || true
}

# ── Helper: push status to a single origin project item ──────────────────────
push_origin_status() {
  local o_project_id="$1" o_item_id="$2" o_project_title="$3" status_name="$4"

  local field_data
  field_data=$(gh api graphql -f query="
    query {
      node(id: \"$o_project_id\") {
        ... on ProjectV2 {
          fields(first: 20) {
            nodes {
              ... on ProjectV2SingleSelectField { id name options { id name } }
            }
          }
        }
      }
    }
  " 2>/dev/null || true)

  [[ -z "$field_data" ]] && { log "    WARN: could not fetch fields for '$o_project_title'"; return; }

  read -r o_field_id o_option_id < <(echo "$field_data" | python3 -c "
$NORMALIZE_PY
import sys, json
target = normalize('$status_name')
d = json.load(sys.stdin)
for node in d['data']['node']['fields']['nodes']:
    if node.get('name') == 'Status':
        fid = node['id']
        for opt in node.get('options', []):
            if normalize(opt['name']) == target:
                print(fid, opt['id'])
                sys.exit(0)
        break
" 2>/dev/null || true)

  if [[ -z "${o_field_id:-}" || -z "${o_option_id:-}" ]]; then
    log "    WARN: '$status_name' not found in '$o_project_title' — skipping"
    return
  fi

  gh api graphql -f query="
    mutation {
      updateProjectV2ItemFieldValue(input: {
        projectId: \"$o_project_id\"
        itemId: \"$o_item_id\"
        fieldId: \"$o_field_id\"
        value: { singleSelectOptionId: \"$o_option_id\" }
      }) { projectV2Item { id } }
    }
  " > /dev/null \
    && log "    ✔ Updated '$o_project_title' → $status_name" \
    || log "    WARN: mutation failed for '$o_project_title'"
}

# ── Step 1: Add open assigned issues ──────────────────────────────────────────
log "=== Step 1: Adding open assigned issues ==="
OPEN_URLS_FILE="$TMPDIR_SYNC/open_urls.txt"
touch "$OPEN_URLS_FILE"

for repo in "${REPOS[@]}"; do
  log "Checking $repo ..."
  issues=$(gh issue list \
    --repo "$repo" \
    --assignee "$ASSIGNEE" \
    --state open \
    --limit 500 \
    --json url \
    --jq '.[].url' 2>/dev/null || true)

  if [[ -z "$issues" ]]; then
    log "  No open assigned issues"
    continue
  fi

  while IFS= read -r url; do
    echo "$url" >> "$OPEN_URLS_FILE"
    log "  Adding: $url"
    gh project item-add "$BOARD_NUMBER" --owner "$BOARD_OWNER" --url "$url" 2>/dev/null || true
  done <<< "$issues"
done

# ── Fetch current personal board state ───────────────────────────────────────
log "=== Fetching personal board state ==="
BOARD_ITEMS_FILE="$TMPDIR_SYNC/board_items.json"
gh project item-list "$BOARD_NUMBER" --owner "$BOARD_OWNER" --limit 500 --format json > "$BOARD_ITEMS_FILE"

# ── Step 2: Detect status changes, emit actions ───────────────────────────────
log "=== Step 2: Detecting status changes ==="
ACTIONS_FILE="$TMPDIR_SYNC/actions.ndjson"

python3 - "$BOARD_ITEMS_FILE" "$OPEN_URLS_FILE" "$STATE_FILE" "$ACTIONS_FILE" \
         "$DONE_STATUS" <<'PYEOF'
import sys, json

board_path, open_urls_path, state_path, actions_path, done_status = sys.argv[1:]

with open(open_urls_path) as f:
    open_urls = set(l.strip() for l in f if l.strip())

with open(state_path) as f:
    state = json.load(f)

with open(board_path) as f:
    data = json.load(f)

actions = []
new_state = dict(state)

for item in data.get('items', []):
    if item.get('content', {}).get('type') != 'Issue':
        continue
    url = item.get('content', {}).get('url', '')
    if not url:
        continue
    item_id       = item['id']
    cur_personal  = item.get('status') or ''
    prev          = state.get(url, {})
    prev_personal = prev.get('personal_status', '')
    is_new        = url not in state

    if url not in open_urls:
        if cur_personal != done_status:
            actions.append({'action': 'SET_DONE', 'itemId': item_id, 'url': url})
        new_state[url] = {**prev, 'personal_status': done_status}
    elif is_new:
        actions.append({'action': 'INHERIT_ORIGIN', 'itemId': item_id, 'url': url})
        new_state[url] = {'personal_status': cur_personal, 'origin_status': ''}
    elif prev_personal and cur_personal != prev_personal:
        actions.append({'action': 'PUSH_TO_ORIGIN', 'itemId': item_id,
                        'url': url, 'status': cur_personal})
        new_state[url] = {**prev, 'personal_status': cur_personal,
                          'origin_status': cur_personal}
    else:
        new_state[url] = {**prev, 'personal_status': cur_personal}

with open(actions_path, 'w') as f:
    for a in actions:
        f.write(json.dumps(a) + '\n')

with open(state_path, 'w') as f:
    json.dump(new_state, f, indent=2)
PYEOF

# ── Step 2b: Execute actions ──────────────────────────────────────────────────
if [[ -s "$ACTIONS_FILE" ]]; then
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    action=$(echo "$line"  | python3 -c "import sys,json; print(json.loads(sys.stdin.read())['action'])")
    item_id=$(echo "$line" | python3 -c "import sys,json; print(json.loads(sys.stdin.read())['itemId'])")
    url=$(echo "$line"     | python3 -c "import sys,json; print(json.loads(sys.stdin.read())['url'])")
    status=$(echo "$line"  | python3 -c "import sys,json; print(json.loads(sys.stdin.read()).get('status',''))" 2>/dev/null || true)

    case "$action" in
      SET_DONE)
        log "  → Stale (closed/unassigned): $url"
        set_personal_status "$item_id" "$DONE_STATUS"
        ;;

      INHERIT_ORIGIN)
        log "  → New item, inheriting origin status: $url"
        origin_status=""
        origin_project_id=""
        while IFS= read -r oi; do
          [[ -z "$oi" ]] && continue
          s=$(echo "$oi" | python3 -c "import sys,json; print(json.loads(sys.stdin.read()).get('status',''))")
          pid=$(echo "$oi" | python3 -c "import sys,json; print(json.loads(sys.stdin.read()).get('projectId',''))")
          if [[ -n "$s" && -z "$origin_status" ]]; then
            origin_status="$s"
            origin_project_id="$pid"
          fi
        done < <(get_origin_project_items "$url")

        if [[ -n "$origin_status" ]]; then
          personal_status=$(translate_status "$origin_project_id" "$origin_status")
          personal_status="${personal_status:-$origin_status}"
          log "    Setting '$personal_status' (from origin: '$origin_status')"
          set_personal_status "$item_id" "$personal_status"
          python3 - "$STATE_FILE" "$url" "$personal_status" <<'PYEOF'
import sys, json
sp, url, status = sys.argv[1], sys.argv[2], sys.argv[3]
with open(sp) as f: state = json.load(f)
state[url] = {'personal_status': status, 'origin_status': status}
with open(sp, 'w') as f: json.dump(state, f, indent=2)
PYEOF
        else
          log "    No origin project status — setting 🆕 New"
          set_personal_status "$item_id" "🆕 New"
        fi
        ;;

      PUSH_TO_ORIGIN)
        log "  → Pushing '$status' to origin: $url"
        while IFS= read -r oi; do
          [[ -z "$oi" ]] && continue
          o_pid=$(echo "$oi"   | python3 -c "import sys,json; print(json.loads(sys.stdin.read())['projectId'])")
          o_iid=$(echo "$oi"   | python3 -c "import sys,json; print(json.loads(sys.stdin.read())['itemId'])")
          o_title=$(echo "$oi" | python3 -c "import sys,json; print(json.loads(sys.stdin.read())['projectTitle'])")
          push_origin_status "$o_pid" "$o_iid" "$o_title" "$status"
        done < <(get_origin_project_items "$url")
        ;;
    esac
  done < "$ACTIONS_FILE"
else
  log "  No status changes to sync."
fi

log "=== Sync complete ==="
