"""focal pm solo — lightweight solo-mode project management via build-log.json.

State lives in  docs/focal/build-log.json  (source of truth).
Rendered view:  docs/build-log.md          (human + agent readable, always re-generated).

Workflow
--------
focal pm solo init   owner/repo   # scaffold + first render
focal pm solo queue  ISSUE BRANCH [--sp N] [--what TEXT]
focal pm solo start  ISSUE                # up_next → in_flight
focal pm solo pr     ISSUE PR             # set PR number on in_flight row
focal pm solo ship   ISSUE [PR]           # in_flight → shipped
focal pm solo note   TEXT                 # update current_state.last_action
focal pm solo render                      # re-render build-log.md from JSON
focal pm solo status [REPO] [--last N]    # terminal summary
focal pm solo sync   REPO [--limit N]     # sync GitHub releases/tags → releases section
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from rich.console import Console
from rich.table import Table

console = Console()

# ── Paths ─────────────────────────────────────────────────────────────────────


def _json_path(repo_root: Path) -> Path:
    return repo_root / "docs" / "focal" / "build-log.json"


def _md_path(repo_root: Path) -> Path:
    return repo_root / "docs" / "build-log.md"


# ── JSON load / save ──────────────────────────────────────────────────────────


def _empty_state(repo: str) -> dict:
    return {
        "repo": repo,
        "current_state": {
            "last_action": "",
            "next_step": "",
        },
        "in_flight": [],
        "up_next": [],
        "shipped": [],
        "releases": [],
    }


def load(repo_root: Path) -> dict:
    p = _json_path(repo_root)
    if not p.exists():
        return _empty_state("")
    return json.loads(p.read_text(encoding="utf-8"))


def save(repo_root: Path, state: dict) -> None:
    p = _json_path(repo_root)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        json.dumps(state, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


# ── Renderer ──────────────────────────────────────────────────────────────────


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    """Render a simple markdown table."""
    divider = "|" + "".join("---|" for _ in headers)
    header = "| " + " | ".join(headers) + " |"
    lines = [header, divider]
    for row in rows:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(lines)


def render(repo_root: Path) -> None:
    """Re-generate docs/build-log.md from docs/focal/build-log.json."""
    state = load(repo_root)
    repo = state.get("repo", "")
    cs = state.get("current_state", {})
    last_action = cs.get("last_action", "")
    next_step = cs.get("next_step", "")

    in_flight = state.get("in_flight", [])
    up_next = state.get("up_next", [])
    shipped = state.get("shipped", [])
    releases = state.get("releases", [])

    lines: list[str] = []

    # Header
    title = f"{repo} — Build Log" if repo else "Build Log"
    lines += [
        f"# {title}",
        "",
        "Running record of what's been shipped, what's in flight, and what's next.",
        "This file is generated by focal — edit via `focal pm solo` commands.",
        "",
        "---",
        "",
    ]

    # Current state
    lines += [
        "## Current state",
        "",
        f"**Last action:** {last_action or '—'}",
        "",
        f"**Next step:** {next_step or '—'}",
        "",
        "---",
        "",
    ]

    # In flight
    lines.append("## In flight")
    lines.append("")
    if in_flight:
        rows = [
            [r["pr"], r["issue"], r["branch"], r["what"], r["state"]] for r in in_flight
        ]
        lines.append(_md_table(["PR", "Issue", "Branch", "What", "State"], rows))
    else:
        lines.append("| PR | Issue | Branch | What | State |")
        lines.append("|---|---|---|---|---|")
    lines += ["", "---", ""]

    # Up next
    lines.append("## Up next")
    lines.append("")
    if up_next:
        rows = [
            [r["rank"], r["issue"], r["branch"], r["sp"], r["what"]] for r in up_next
        ]
        lines.append(_md_table(["Rank", "Issue", "Branch", "SP", "What"], rows))
    else:
        lines.append("| Rank | Issue | Branch | SP | What |")
        lines.append("|---|---|---|---|---|")
    lines += ["", "---", ""]

    # Shipped
    lines.append("## Shipped")
    lines.append("")
    if shipped:
        rows = [
            [
                r["pr"],
                r["issue"],
                r.get("shipped_at", "—"),
                r.get("release") or "—",
                r["what"],
            ]
            for r in shipped
        ]
        lines.append(_md_table(["PR", "Issue", "Date", "Release", "What"], rows))
    else:
        lines.append("| PR | Issue | Date | Release | What |")
        lines.append("|---|---|---|---|---|")
    lines += ["", "---", ""]

    # Releases
    lines.append("## Releases")
    lines.append("")
    lines.append("_Synced from GitHub. Run `focal pm solo sync` to refresh._")
    lines.append("")
    if releases:
        rows = []
        for r in releases:
            pre = " _(pre)_" if r.get("prerelease") else ""
            version_cell = (
                f"[{r['version']}]({r['url']})" if r.get("url") else r["version"]
            )
            rows.append(
                [version_cell + pre, r.get("published_at", "—"), r.get("body", "—")]
            )
        lines.append(_md_table(["Version", "Date", "Notes"], rows))
    else:
        lines.append("| Version | Date | Notes |")
        lines.append("|---|---|---|")
    lines += ["", "---", ""]

    md = "\n".join(lines)
    _md_path(repo_root).parent.mkdir(parents=True, exist_ok=True)
    _md_path(repo_root).write_text(md, encoding="utf-8")


# ── Commands ──────────────────────────────────────────────────────────────────


def init(repo: str, repo_root: Path) -> None:
    """Scaffold build-log.json and render build-log.md."""
    json_p = _json_path(repo_root)
    if json_p.exists():
        console.print(
            f"  [dim]{json_p.relative_to(repo_root)} already exists — skipping[/dim]"
        )
    else:
        json_p.parent.mkdir(parents=True, exist_ok=True)
        save(repo_root, _empty_state(repo))
        console.print(f"  [green]✔[/green] {json_p.relative_to(repo_root)}")

    render(repo_root)
    console.print(f"  [green]✔[/green] {_md_path(repo_root).relative_to(repo_root)}")

    console.print("\n[bold green]Solo init complete![/bold green]\n")
    console.print("Next steps:")
    console.print(
        "  1. Queue your first task:  [bold]focal pm solo queue #N branch-name --sp 3 --what 'description'[/bold]"
    )
    console.print(
        f"  2. Check status:           [bold]focal pm solo status {repo}[/bold]"
    )
    console.print(
        "  3. Commit the scaffold:    [bold]git add docs/ && git commit -m 'chore: focal solo init'[/bold]"
    )


def queue(
    repo_root: Path,
    issue: str,
    branch: str,
    sp: int = 0,
    what: str = "",
) -> None:
    """Add an item to ## Up next."""
    state = load(repo_root)
    up_next: list[dict] = state.setdefault("up_next", [])

    # Idempotent — update if issue already exists
    for row in up_next:
        if row.get("issue") == issue:
            row.update({"branch": branch, "sp": sp, "what": what})
            console.print(f"  [yellow]↺[/yellow]  Updated {issue} in Up next")
            save(repo_root, state)
            render(repo_root)
            return

    rank = max((r.get("rank", 0) for r in up_next), default=0) + 1
    up_next.append(
        {"rank": rank, "issue": issue, "branch": branch, "sp": sp, "what": what}
    )
    save(repo_root, state)
    render(repo_root)
    console.print(f"  [green]✔[/green] Queued {issue} as rank {rank}")


def start(repo_root: Path, issue: str) -> None:
    """Move an item from Up next → In flight."""
    state = load(repo_root)
    up_next: list[dict] = state.get("up_next", [])
    in_flight: list[dict] = state.setdefault("in_flight", [])

    row = next((r for r in up_next if r.get("issue") == issue), None)
    if row is None:
        console.print(f"  [red]✗[/red]  {issue} not found in Up next")
        return

    state["up_next"] = [r for r in up_next if r.get("issue") != issue]
    # Re-rank remaining
    for i, r in enumerate(state["up_next"], start=1):
        r["rank"] = i

    in_flight.append(
        {
            "pr": "—",
            "issue": issue,
            "branch": row.get("branch", ""),
            "what": row.get("what", ""),
            "state": "🔄",
        }
    )
    save(repo_root, state)
    render(repo_root)
    console.print(f"  [green]✔[/green] {issue} moved to In flight")


def set_pr(repo_root: Path, issue: str, pr: str) -> None:
    """Set the PR number on an In flight row."""
    state = load(repo_root)
    in_flight: list[dict] = state.get("in_flight", [])

    row = next((r for r in in_flight if r.get("issue") == issue), None)
    if row is None:
        console.print(f"  [red]✗[/red]  {issue} not found in In flight")
        return

    pr_str = pr if pr.startswith("#") else f"#{pr}"
    row["pr"] = pr_str
    save(repo_root, state)
    render(repo_root)
    console.print(f"  [green]✔[/green] {issue} PR set to {pr_str}")


def ship(repo_root: Path, issue: str, pr: str | None = None) -> None:
    """Move an item from In flight → Shipped (prepended, most recent first)."""
    state = load(repo_root)
    in_flight: list[dict] = state.get("in_flight", [])
    shipped: list[dict] = state.setdefault("shipped", [])

    row = next((r for r in in_flight if r.get("issue") == issue), None)
    if row is None:
        console.print(f"  [red]✗[/red]  {issue} not found in In flight")
        return

    state["in_flight"] = [r for r in in_flight if r.get("issue") != issue]

    pr_str = row.get("pr", "—")
    if pr:
        pr_str = pr if pr.startswith("#") else f"#{pr}"

    shipped.insert(
        0,
        {
            "pr": pr_str,
            "issue": issue,
            "what": row.get("what", ""),
            "shipped_at": date.today().isoformat(),
            "release": "",
        },
    )
    save(repo_root, state)
    render(repo_root)
    console.print(f"  [green]✔[/green] {issue} shipped (PR {pr_str})")


def note(repo_root: Path, text: str) -> None:
    """Update the Last action line in Current state."""
    state = load(repo_root)
    state.setdefault("current_state", {})["last_action"] = text
    save(repo_root, state)
    render(repo_root)
    console.print("  [green]✔[/green] Note updated")


def sync(repo: str, repo_root: Path, limit: int = 10) -> dict:
    """Fetch GitHub releases for *repo* and update the releases section in build-log.json.

    Uses ``gh release list`` — requires the gh CLI to be authenticated.
    Returns a summary dict suitable for MCP tool responses.
    """
    import subprocess

    result = subprocess.run(
        [
            "gh",
            "release",
            "list",
            "--repo",
            repo,
            "--limit",
            str(limit),
            "--json",
            "tagName,publishedAt,isPrerelease,name",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        msg = result.stderr.strip() or "gh release list failed"
        console.print(f"  [red]✗[/red]  {msg}")
        return {"ok": False, "error": msg}

    raw: list[dict] = json.loads(result.stdout or "[]")

    releases = []
    for r in raw:
        tag = r.get("tagName", "")
        # Derive URL from repo + tag (gh release list doesn't expose url as a JSON field)
        url = f"https://github.com/{repo}/releases/tag/{tag}" if tag else ""
        # Use the release name as the notes column (it's the human-readable title)
        notes = (r.get("name") or "").strip()
        releases.append(
            {
                "version": tag,
                "name": notes,
                "tag": tag,
                "published_at": (r.get("publishedAt", "") or "")[:10],  # date only
                "url": url,
                "prerelease": bool(r.get("isPrerelease")),
                "body": notes,
            }
        )

    state = load(repo_root)
    state["releases"] = releases

    # ── Correlate shipped rows with releases ──────────────────────────────────
    # Sort releases oldest-first for the scan; each shipped row gets tagged with
    # the earliest release whose published_at >= shipped_at.
    releases_asc = sorted(
        [r for r in releases if r.get("published_at")],
        key=lambda r: r["published_at"],
    )
    correlated = 0
    for row in state.get("shipped", []):
        shipped_at = row.get("shipped_at", "")
        if not shipped_at:
            continue
        matched = next(
            (r for r in releases_asc if r["published_at"] >= shipped_at), None
        )
        new_release = matched["version"] if matched else ""
        if row.get("release") != new_release:
            row["release"] = new_release
            correlated += 1

    save(repo_root, state)
    render(repo_root)

    count = len(releases)
    latest = releases[0]["version"] if releases else "—"
    console.print(f"  [green]✔[/green] Synced {count} release(s) — latest: {latest}")
    if correlated:
        console.print(
            f"  [green]✔[/green] Correlated {correlated} shipped item(s) with releases"
        )
    return {"ok": True, "count": count, "latest": latest, "releases": releases}


def status(repo_root: Path, repo: str = "", last: int = 5) -> None:
    """Print a terminal summary from build-log.json."""
    json_p = _json_path(repo_root)
    if not json_p.exists():
        console.print(
            "[red]build-log.json not found.[/red] "
            f"Run [bold]focal pm solo init {repo or 'owner/repo'}[/bold] first."
        )
        return

    state = load(repo_root)
    label = state.get("repo") or repo or "local"

    console.print(f"\n[bold cyan]  ◎  Focal — solo status ({label})[/bold cyan]\n")

    cs = state.get("current_state", {})
    last_action = cs.get("last_action", "")
    next_step = cs.get("next_step", "")
    if last_action:
        console.print(f"  [dim]Last action:[/dim]  {last_action}")
    if next_step:
        console.print(f"  [dim]Next step:  [/dim]  {next_step}")
    if last_action or next_step:
        console.print()

    # In flight
    in_flight = state.get("in_flight", [])
    count = len(in_flight)
    noun = "item" if count == 1 else "items"
    console.print(f"[bold]In flight[/bold]  · {count} {noun}")
    console.rule()
    if in_flight:
        t = Table(show_header=True, header_style="bold", box=None, padding=(0, 1))
        t.add_column("PR")
        t.add_column("Issue")
        t.add_column("Branch")
        t.add_column("What")
        t.add_column("State")
        for r in in_flight:
            t.add_row(r["pr"], r["issue"], r["branch"], r["what"], r["state"])
        console.print(t)
    else:
        console.print("  [dim]Nothing in flight.[/dim]")
    console.print()

    # Up next
    up_next = state.get("up_next", [])
    count = len(up_next)
    noun = "item" if count == 1 else "items"
    total_sp = sum(r.get("sp", 0) for r in up_next)
    sp_label = f"  · {total_sp} SP" if total_sp else ""
    console.print(f"[bold]Up next[/bold]  · {count} {noun}{sp_label}")
    console.rule()
    if up_next:
        t = Table(show_header=True, header_style="bold", box=None, padding=(0, 1))
        t.add_column("Rank", justify="right")
        t.add_column("Issue")
        t.add_column("Branch")
        t.add_column("SP", justify="right")
        t.add_column("What")
        for r in up_next:
            t.add_row(
                str(r.get("rank", "")),
                r["issue"],
                r["branch"],
                str(r["sp"]) if r.get("sp") else "—",
                r["what"],
            )
        console.print(t)
    else:
        console.print("  [dim]Nothing up next.[/dim]")
    console.print()

    # Shipped
    shipped_slice = state.get("shipped", [])[:last]
    count = len(shipped_slice)
    noun = "item" if count == 1 else "items"
    console.print(f"[bold]Recently shipped[/bold]  · last {last}  · {count} {noun}")
    console.rule()
    if shipped_slice:
        t = Table(show_header=True, header_style="bold", box=None, padding=(0, 1))
        t.add_column("PR")
        t.add_column("Issue")
        t.add_column("Date")
        t.add_column("Release")
        t.add_column("What")
        for r in shipped_slice:
            release_val = r.get("release") or "[dim]—[/dim]"
            t.add_row(
                r["pr"],
                r["issue"],
                r.get("shipped_at", "—"),
                release_val,
                r["what"],
            )
        console.print(t)
    else:
        console.print("  [dim]Nothing shipped yet.[/dim]")
    console.print()

    # Releases
    releases = state.get("releases", [])
    if releases:
        latest = releases[0]
        pre_tag = " [dim](pre)[/dim]" if latest.get("prerelease") else ""
        console.print(f"[bold]Releases[/bold]  · {len(releases)} synced")
        console.rule()
        t = Table(show_header=True, header_style="bold", box=None, padding=(0, 1))
        t.add_column("Version")
        t.add_column("Date")
        t.add_column("Notes")
        for r in releases[:5]:
            pre = " (pre)" if r.get("prerelease") else ""
            t.add_row(
                r["version"] + pre, r.get("published_at", "—"), r.get("body", "—")
            )
        console.print(t)
        console.print(
            f"\n  [dim]Latest:[/dim] {latest['version']}{pre_tag}  "
            f"[dim]({latest.get('published_at', '—')})[/dim]"
        )
        console.print()
    else:
        console.print("[bold]Releases[/bold]")
        console.rule()
        console.print(
            "  [dim]No releases synced yet. Run [bold]focal pm solo sync "
            f"{repo or 'owner/repo'}[/bold] to fetch from GitHub.[/dim]"
        )
        console.print()
